const caracteristicasEnToEs ={
    marca:"Marca",
    pci:"Pci",
    capacity:"Capacidad",
    type:"Tipo",
    interfaz:"Interfaz",
    cooler:"Disipador",
    graphics:"Graficos",
    ram:"Compatibilidad de Ram",
    socket:"Socket",
    ddr:"DDR",
    bus:"Velocidad",
    speed:"Velocidad",
    stock:"Stock",
    pantalla:"Pantalla",
    procesador:"Procesador",
    RAM:"RAM",
    Almacenamiento:"Almacenamiento",
    conectividad:"Conectividad",
    os:"OS",
    tecladoBacklit:"Teclado retroiluminado",
    fingerPrint:"Lector de huella",
    chipset:"Chipset",
    ramSlots:"Solts para RAM",
    mDos:"Puertos M.2 ",
    factor:"Factor de forma",
    certification:"Certificación",
    conectores:"Conectores",
    potencia:"Potencia",
    cable:"Cable de poder",
    formato:"Formato",
    motherboards:"Tamaño motherboard",
    dimensiones:"Dimensiones",
    fuente:"Fuente de poder",
    ventiladores:"Ventiladores",
    entradas:"Conexiones",
    screenType:"Tipo de panel",
    respuesta:"Latencia",
    resolution:"Resolución",
    proportion:"Proporción",
    refresco:"Tasa de refresco",
    tamaño:"Tamaño",
    curvo:"Pantalla curva",
    botones:"Botones",
    DPI:"DPI",
    programable:"Programables",
    RGB:"RGB",
    keyBoardType:"Tipo",
    switchType:"Tipo de switch",
    backlit:"Retroiluminado",
    audioSys:"Sistema de audio",
    conector:"Conector",
    microfono:"Microfono",
    frecuencia:"Frecuencia",
    sensibilidad:"Sensibilidad",
    intervalo:"Intervalo",
    cod:"Cod"
};

export {
    caracteristicasEnToEs,
}